sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kacv0RptxXn7gPMDhBe7BG676Ev8/kXlFBk5RMwLSI81VfewbykQWrWSFoOThvOJmy02MNQuOHQhoz/9wopykzZx9WJvZ66SRZg+7X24aH42WedJtNIsCYf/FqYRXgq0O9Hg09srXyHmMx+kMcOZSdFhyKcdBHAgprlcroXJVkRkgM4lz6SiiRdIqcWWxrSOJ7euAACuD5vbdV5AAj9AhZYtITCijZ7hNGQVLZaB/6YzXl+XetHiZMNjh3YI5DhphceuiCpOxzPgKqlBeZilw6FwS2l9sttPhujbO4BsA8/AZECuCaVW4pDD3tWmCYkMQosPq7vfGs1Y4il+oMamOzG6hEHqGhg3p/hm0ouYVuELyMP2TVJT4XdxGKcgWH7I1jY4USaXNdT1kdlVaIVgRGQpdR2Pd+KdJZd2EFhrNGeeiW5m6CqdIqLh4Iq8gIew0hboA4ncOpoA/39gOo3v1AqZVXqdLBxfV/ncd7H3Q/eBIT7BVG2k2+D5hkWWY7dNA9dDEvUC0+8lXkVtx5E81fMECwyFaSbtx3lMAinOf0wVSdtFZCuMPztNf7cv9jPk2f+b7YIXR8e1FgXOjl9w2k27uAvHJkLa8I3sPZhzTqMyEWtrh2XDqo1u0OBK5WrSRa+T0LzGBUh4g298rPgDPQrpmx+tFpZY0TxLYnC+kJI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Divine-Comedy-Volume-2-Purgatory_1996
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy